config/routes.rb
Rails.application.routes.draw do
  root to: "tops#index"
  resources :tops, only: :index do
    collection do
      get 'first_content'
      get 'second_content'
      get 'third_content'
      get 'fourth_content'
      get 'fifth_content'
      get 'six_content'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController

    def index
    end

    def first_content
        render layout: false
    end

    def second_content
        render layout: false
    end

    def third_content
        render layout: false
    end

    def fourth_content
        render layout: false
    end

    def fifth_content
        render layout: false
    end

    def six_content
        render layout: false
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FrontEndApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%# ヘッダー %>
      <header class="header">
        <div class="area_logo">
          <%= link_to image_tag("front.png", class: :logo), root_path %>
        </div>
        <div class="header_menu">
          <a href="#scroll1" class="nav_btn">About</a>
          <a href="#scroll2" class="nav_btn">Works</a>
        </div>
      </header>
    <%# ヘッダー %>
    
    <%# メイン %>
      <%= yield %>
    <%# メイン %>

    <%# フッター %>
      <footer>
        <div class="footer_area">
          <div class="top_btn" id="btn">トップへ</div>
          <p class="copyright">Copyright © front end app All Rights Reserved.</p>
        </div>
      </footer>
    <%# フッター %>
    
  </body>
</html>

app/views/tops/fifth_content.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Xeory Extension</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" rel="stylesheet">
  </head>
  <body>
  <%# ヘッダー %>
    <header class="xeory_header">
      <%= link_to "Xeory Extension", fifth_content_tops_path, class: :xeory_logo %>
      <div class="xeory_nav_area">
        <ul>
            <li>記事ページサンプル</li>
            <li>Extensionをダウンロード</li>
        </ul>
      </div>
    </header>
  <%# ヘッダー %>

  <%# ヘッダー下の説明 %>
  <div class="xeory_header_bottom_area">
    <h2>Xeory Extension</h2>
    <p>Xeory Extensionはワンコラムのサイト型テーマです。ユーザーに対して重要なコンテンツを効率的に届けられるようにデザインされています。５種類のカラーバリエーションを用意しています。</p>
  </div>
  <%# ヘッダー下の説明 %>

  <%# メイン %>
  <div class="xeory_main_area">

    <%# コンテンツ同士の隙間 %>
      <div class="xeory_gap"></div>
    <%# コンテンツ同士の隙間 %>

    <%# 人気のある記事 %>
    <section class="popular_articles_area">
      <div class="popular_articles">
        <h2>人気のある記事</h2>
      </div>
      <div class="xeory_wrap">
          <div class="xeory_popular_contents">
            <article class="xeory_popular_content">
              <%= link_to image_tag("under.png", class: :xeory_popular_img), fifth_content_tops_path %>
              <p>カテゴリー#1</p>
              <h3>テスト投稿</h3>
            </article>
            <article class="xeory_popular_content">
              <%= link_to image_tag("under.png", class: :xeory_popular_img), fifth_content_tops_path %>
              <p>カテゴリー#1</p>
              <h3>テスト投稿</h3>
            </article>
            <article class="xeory_popular_content">
              <%= link_to image_tag("under.png", class: :xeory_popular_img), fifth_content_tops_path %>
              <p>カテゴリー#1</p>
              <h3>テスト投稿</h3>
            </article>
            <article class="xeory_popular_content">
              <%= link_to image_tag("under.png", class: :xeory_popular_img), fifth_content_tops_path %>
              <p>カテゴリー#1</p>
              <h3>テスト投稿</h3>
            </article>
            <article class="xeory_popular_content">
              <%= link_to image_tag("under.png", class: :xeory_popular_img), fifth_content_tops_path %>
              <p>カテゴリー#1</p>
              <h3>テスト投稿</h3>
            </article>
          </div>
      </div>
    <section>
    <%# 人気のある記事 %>

    <%# コンテンツ同士の隙間 %>
      <div class="xeory_gap"></div>
    <%# コンテンツ同士の隙間 %>

    <%# 最近の投稿 %>
    <section class="popular_articles_area">
      <div class="popular_articles">
        <h2>最近の投稿</h2>
      </div>
      <div class="xeory_wrap">
          <div class="xeory_popular_contents">
            <article class="xeory_popular_content">
              <%= link_to image_tag("under.png", class: :xeory_popular_img), fifth_content_tops_path %>
              <p>カテゴリー#1</p>
              <h3>テスト投稿</h3>
            </article>
            <article class="xeory_popular_content">
              <%= link_to image_tag("under.png", class: :xeory_popular_img), fifth_content_tops_path %>
              <p>カテゴリー#1</p>
              <h3>テスト投稿</h3>
            </article>
            <article class="xeory_popular_content">
              <%= link_to image_tag("under.png", class: :xeory_popular_img), fifth_content_tops_path %>
              <p>カテゴリー#1</p>
              <h3>テスト投稿</h3>
            </article>
            <article class="xeory_popular_content">
              <%= link_to image_tag("under.png", class: :xeory_popular_img), fifth_content_tops_path %>
              <p>カテゴリー#1</p>
              <h3>テスト投稿</h3>
            </article>
            <article class="xeory_popular_content">
              <%= link_to image_tag("under.png", class: :xeory_popular_img), fifth_content_tops_path %>
              <p>カテゴリー#1</p>
              <h3>テスト投稿</h3>
            </article>
          </div>
      </div>
    </section>
    <%# 最近の投稿 %>

    <%# コンテンツ同士の隙間 %>
      <div class="xeory_gap"></div>
    <%# コンテンツ同士の隙間 %>

    <%# 特徴 %>
      <section class="xeory_feature_area">
        <div class="xeory_feature_header">
          <i class="fas fa-check"></i>
          <h2>XeoryExtensionの特徴</h2>
          <p>feature</p>
        </div>

        <%# モバイルレスポンシブ %>
          <section class="xeory_feature_main_area">
            <div class="xeory_feature_wrap">
              <div class="xeory_feature_box">
                <div class="xeory_feature_inner">
                  <div class="xeory_feature_title">
                    <p class="xeory_feature_number">1</p>
                    <h3 class="xeory_feature_ttl">モバイルレスポンシブ</h3>
                    <p class="xeory_feature_english">Mobile Responsive</p>
                    <p>Xeory Extensionはレスポンシブデザインを採用しています。スマートフォンやタブレットなど各種デバイスで表示が最適化されます。</p>
                    <p class="xeory_feature_btn">詳しく見る</p>
                  </div>
                </div>
                <div>
                  <%= image_tag("under.png", class: :xeory_feature_right_img) %>
                </div>
              </div>
            </div>
          </section>
        <%# モバイルレスポンシブ %>

        <%# HTML5デザイン %>
          <section class="xeory_feature_main_area2">
            <div class="xeory_feature_wrap">
              <div class="xeory_feature_box">
                <div>
                  <%= image_tag("under.png", class: :xeory_feature_left_img) %>
                </div>
                <div class="xeory_feature_inner2">
                  <div class="xeory_feature_title">
                    <p class="xeory_feature_number">2</p>
                    <h3 class="xeory_feature_ttl">HTML5デザイン</h3>
                    <p class="xeory_feature_english">HTML5 Design</p>
                    <p>Xeory Extensionは最新のHTML5言語でデザイン及びコーディングがなされています。時代遅れのソースからは卒業しましょう。</p>
                    <p class="xeory_feature_btn">詳しく見る</p>
                  </div>
                </div>
              </div>
            </div>
          </section>
        <%# HTML5デザイン %>

        <%# SEO最適化 %>
          <section class="xeory_feature_main_area">
            <div class="xeory_feature_wrap">
              <div class="xeory_feature_box">
                <div class="xeory_feature_inner">
                  <div class="xeory_feature_title">
                    <p class="xeory_feature_number">3</p>
                    <h3 class="xeory_feature_ttl">SEO最適化</h3>
                    <p class="xeory_feature_english">Search Engine Optimized</p>
                    <p>Xeory ExtensionはGoogleのSEOガイドラインに可能な限り沿った構造になっています。必要なのは良質なコンテンツだけです。</p>
                    <p class="xeory_feature_btn">詳しく見る</p>
                  </div>
                </div>
                <div>
                  <%= image_tag("under.png", class: :xeory_feature_right_img) %>
                </div>
              </div>
            </div>
          </section>
        <%# SEO最適化 %>

        <%# 高いカスタマイズ性 %>
          <section class="xeory_feature_main_area2">
            <div class="xeory_feature_wrap">
              <div class="xeory_feature_box">
                <div>
                  <%= image_tag("under.png", class: :xeory_feature_left_img) %>
                </div>
                <div class="xeory_feature_inner2">
                  <div class="xeory_feature_title">
                    <p class="xeory_feature_number">4</p>
                    <h3 class="xeory_feature_ttl">高いカスタマイズ性</h3>
                    <p class="xeory_feature_english">Customizable</p>
                    <p>Xeory Extensionはカスタマイズフリーです。CSS, HTML, PHP の知識があれば自由にカスタマイズすることができます。</p>
                    <p class="xeory_feature_btn">詳しく見る</p>
                  </div>
                </div>
              </div>
            </div>
          </section>
        <%# 高いカスタマイズ性 %>
      </section>
    <%# 特徴 %>

    <%# サービス紹介 %>
      <section class="xeory_feature_area">
        <div class="xeory_feature_header">
          <i class="fas fa-check"></i>
          <h2>サービス紹介</h2>
          <p>service</p>
        </div>
        <div class="xeory_feature_wrap">
          <div class="xeory_service_inner">
            <section class="xeory_service_box">
              <div class="xeory_service_ttl">
                <h3>Xeoryカスタマイズ</h3>
                <p class="xeory_service_english">Xeory Customize</p>
                <p class="xeory_service_btn">カスタマイズ事例を見る</p>
              </div>
            </section>
            <section class="xeory_service_box2">
              <div class="xeory_service_ttl">
                <h3>コンサルティング</h3>
                <p class="xeory_service_english">Consulting</p>
                <p class="xeory_service_btn">コンサルティング事例を見る</p>
              </div>
            </section>
          </div>
        </div>
      </section>
    <%# サービス紹介 %>

    <%# 会社紹介 %>
      <section class="xeory_feature_area">
        <div class="xeory_feature_header">
          <i class="fas fa-check"></i>
          <h2>会社紹介</h2>
          <p>company</p>
        </div>
        <div class="xeory_i_main">
          <div class="xeory_i_img">
            <%= image_tag("xeory_img.png") %>
          </div>
          <div class="xeory_feature_wrap">
            <div class="xeory_i_inner">
              <dl class="front-company">
                <span class="xeory_dt">会社名</span>
                <span class="xeory_dd1">株式会社〇〇〇〇</span>
              </dl>
              <dl class="front-company">
                  <span class="xeory_dt">電話番号</span>
                  <span class="xeory_dd2">000-0000-0000</span>
              </dl>
              <dl class="front-company">
                  <span class="xeory_dt">住所</span>
                  <span class="xeory_dd3">東京都渋谷区</span>
              </dl>
            </div>
          </div>
        </div>
      </section>
    <%# 会社紹介 %>

    <%# お問い合わせ %>
      <section class="xeory_feature_area">
        <div class="xeory_feature_header">
          <i class="fas fa-check"></i>
          <h2>お問い合わせ</h2>
          <p>inquiry</p>
        </div>
        <div class="xeory_f_main">
          <div class="xeory_feature_wrap">
            <div class="xeory_f_inner">
              <form action="#" method="#">
                <dl>
                  <dt>
                    <label for="name" class="xeory_form_name">お名前（必須）</label>
                  </dt>
                  <dd>
                    <input type="text" id="name" name="your-name" class="xeory_form">
                  </dd>
                  <dt>
                    <label for="e-mail" class="xeory_form_name">メールアドレス（必須）</label>
                  </dt>
                  <dd>
                    <input type="email" id="email" name="your-email" class="xeory_form">
                  </dd>
                  <dt>
                    <label for="e-mail" class="xeory_form_name">題名（必須）</label>
                  </dt>
                  <dd>
                    <input type="email" id="email" name="your-email" class="xeory_form">
                  </dd>
                  <dt>
                    <label for="message" class="xeory_form_name">メッセージ本文</label>
                  </dt>
                  <dd>
                    <textarea name="your-message" id="message" class="xeory_form_description" ></textarea>
                  </dd>
                </dl>
                <div class="mywork_btn">
                  <input type="submit" value="送信" class="xeory_send">
                </div>
              </form>
            </div>
          </div>
        </div>
      </section>
    <%# お問い合わせ %>

    <%# フッター %>
      <section class="xeory_f">
        <div class="xeory_f_1">
          <div class="xeory_f_wrap">
            <div class="xeory_f_brand_area">
              <div class="xeory_f_logo">XeoryExtension</div>
            </div>
            <div class="xeory_f_c_area">
              <div class="xeory_f_l_area">
                <div class="row">
                  <div class="xeory_f_cont_content">
                    <h4>ブログコンテンツ</h4>
                  </div>
                  <div class="xeory_f_sns_content">
                    <h4>ソーシャルメディア</h4>
                  </div>
                </div>
              </div>
              <div class="xeory_f_r_area">
                <div class="row">
                  <div class="xeory_footer_img">
                    <%= image_tag("under.png", class: :xeory_f_img) %>
                  </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <div class="xeory_under_f">
        <div class="xeory_under_f_wrap">
          <p>© Copyright 2021 XeoryExtension. All rights reserved.</p>
        </div>
      </div>
    <%# フッター %>
  
  </div>
  <%# メイン %>

  </body>
</html>

app/views/tops/fourth_content.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Mag88</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" rel="stylesheet">
  </head>
  <body>
    
    <%# ヘッダー画像 %>
      <div class="p_img" style="background-image: url('<%= asset_path('fourth.png') %>')");></div>
    <%# ヘッダー画像 %>

    <%# magazine %>
      <section class="magazine">
        <h2>A special, long article in a newspaper or magazine</h2>
        <p>テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト<br>テキストテキストテキストテキストテキストテキスト</p>
        <div class="mag88_two_layout">
          <%= image_tag("mag88_left.png", class: :mag88_magazine_content) %>
          <%= image_tag("mag88_right.png", class: :mag88_magazine_content) %>
        </div>
      </section>
    <%# magazine %>

    <%# fashion %>
      <section class="fashion">
        <div class="fashion_wrapper">
          <h2>Fashion & Style</h2>
          <p>テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト<br>テキストテキストテキストテキストテキストテキスト</p>
          <%= link_to "Read More", fourth_content_tops_path, class: :mag88_fashion_btn %>
        </div>
        <%= image_tag("mag88_pc.png", class: :mag88_pc_img) %>
      </section>
    <%# fashion %>

    <%# Catalog & Antique %>
      <section class="catalog">
        <div class="mag88_two_layout">
          <%= image_tag("catalog_top.png", class: :mag88_magazine_content) %>
          <div class="catalog_description">
            <h2 class="mag88_sec_title"><b>Catalog</b></h2>
            <p>テキストテキストテキストテキストテキストテキストテキストテキストテキスト テキストテキストテキストテキストテキストテキストテキストテキストテキスト テキストテキストテキストテキストテキストテキストテキストテキストテキスト</p>
            <p>テキストテキストテキストテキストテキストテキストテキストテキストテキスト テキストテキストテキストテキストテキストテキストテキストテキストテキスト テキストテキストテキストテキストテキストテキストテキストテキストテキスト</p>
            <p>テキストテキストテキストテキストテキストテキストテキストテキストテキスト テキストテキストテキストテキストテキストテキストテキストテキストテキスト テキストテキストテキストテキストテキストテキストテキストテキストテキスト</p>
          </div>
        </div>
        <div class="mag88_two_layout">
          <div class="catalog_description">
            <h2 class="mag88_sec_title"><b>Antique</b></h2>
            <p>テキストテキストテキストテキストテキストテキストテキストテキストテキスト テキストテキストテキストテキストテキストテキストテキストテキストテキスト テキストテキストテキストテキストテキストテキストテキストテキストテキスト</p>
            <p>テキストテキストテキストテキストテキストテキストテキストテキストテキスト テキストテキストテキストテキストテキストテキストテキストテキストテキスト テキストテキストテキストテキストテキストテキストテキストテキストテキスト</p>
            <%= link_to "Read More", fourth_content_tops_path, class: :mag88_fashion_btn %>
          </div>
          <%= image_tag("catalog_under.png", class: :mag88_magazine_content) %>
        </div>
      </section>
    <%# Catalog & Antique %>

    <%# フッター %>
      <footer>
        <div class="mag88_footer">
          <div class="mag88_item">
            <%= image_tag("mag88_footer_logo.png", class: :mag88_footer_logo) %>
          </div>
          <div class="mag88_item">
            <p>タイトル</p>
            <ul>
              <li>テキストテキストテキスト</li>
              <li>テキストテキストテキスト</li>
              <li>テキストテキストテキスト</li>
              <li>テキストテキストテキスト</li>
              <li>テキストテキストテキスト</li>
            </ul>
          </div>
          <div class="mag88_item">
            <p>タイトルタイトルタイトル</p>
            <h6>テキストテキストテキストテキストテキストテキストテキストテキストテキスト テキストテキストテキストテキストテキストテキストテキストテキストテキスト テキストテキストテキストテキストテキストテキストテキストテキストテキスト</h6>
          </div>
        </div>
        <div class="mag88_copy_right">
          <p>© Mag88</p>
        </div>
      </footer>
    <%# フッター %>
  </body>
</html>

app/views/tops/index.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="style.css">
    <title>front end app</title>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
  </head>
  <body>

  <%# メイン %>

    <%# 隙間 %>
      <div class="area_gap"></div>
    <%# 隙間 %>
    
    <%# About %>
      <div class="about_area" id="scroll1">
        <div class="area_title anime_up anime_op">
          About
        </div>
        <div class="content anime_up anime_op">
          <%= image_tag("pc2.png", class: :about_image) %>
          <div class="about_description">
            <p class="description_title">フロント作品紹介アプリ</p>
            <p>ー概要ー<br>フロント練習した時の作品を紹介する為のアプリ。</p>
            <p>ー言語ー<br>HTML5/CSS3/Javascript/jQuery/など</p>
          </div>
        </div>
      </div>
    <%# About %>

    <%# 隙間 %>
      <div class="area_gap"></div>
    <%# 隙間 %>

    <%# Works %>
      <div class="about_area" id="scroll2">
        <div class="works_area anime_up anime_op">
          <div class="container">
            <div class="area_title">
              Works
            </div>
            <div class="body_home">
              <ul class="list_feature">
                <li class="anime_up anime_op">
                  <%= image_tag 'https://i.gyazo.com/ba3b0349cc3bfc6abe7d1d39b29586e8.gif', size: '300x200' %>
                  <p class="ttl"><%= link_to "FLOWER", first_content_tops_path, class: :function_list %></p>
                  <p class="description">FLOWERのサイトを模写しました。<br>自分以外の方の作品を模写することによって、今まで自分が開発で使わなかった知識も知ることができ、スキルアップにつなげることが出来ました。</p>
                </li>
                <li class="anime_up anime_op">
                  <%= image_tag 'https://i.gyazo.com/48e9d946367bba0beebd8cbc03c796fb.gif', size: '300x200' %>
                  <p class="ttl"><%= link_to "My Work", second_content_tops_path, class: :function_list %></p>
                  <p class="description">My workのサイトを模写しました。<br>この模写をする上で気をつけたポイントは、質の高いHTMLとCSSの記述をしたことです。その為Sassの記述方法も学び、活用しました。</p>
                </li>
                <li class="anime_up anime_op">
                  <%= image_tag 'https://i.gyazo.com/2186d181ed25260260962cefaecae73e.gif', size: '300x200' %>
                  <p class="ttl"><%= link_to "PAS-POL", third_content_tops_path, class: :function_list %></p>
                  <p class="description">PAS-POLのサイトを模写しました。<br>cssによって今まで行った事のない表現方法などを学びました。またデザインの基本四原則についても学び、模写しながら身につけました。</p>
                </li>
              </ul>

              <%# 隙間 %>
                <div class="index_content_gap"></div>
              <%# 隙間 %>

              <ul class="list_feature">
                <li class="anime_up anime_op">
                  <%= image_tag 'https://i.gyazo.com/62daef1f108ca0b8cd5112476acf5622.gif', size: '300x200' %>
                  <p class="ttl"><%= link_to "Mag88", fourth_content_tops_path, class: :function_list %></p>
                  <p class="description">Mag88のサイトを模写しました。<br>今まで実践したことの無いcssの指定方法で要素を表現しました。またcssを再利用するなど業務の効率化なども視野に入れながら開発(模写)を行いました。</p>
                </li>
                <li class="anime_up anime_op">
                  <%= image_tag 'https://i.gyazo.com/539576c74957004a42aa7851b943ec36.gif', size: '300x200' %>
                  <p class="ttl"><%= link_to "Xeory", fifth_content_tops_path, class: :function_list %></p>
                  <p class="description">xeoryのサイトを模写しました。<br>外部のサイトからロゴを引用してくる記述など、まだ慣れていない技術も積極的に取り入れました。デザイン四原則も意識しながら、模写に取り組みました。</p>
                </li>
                <li class="anime_up anime_op">
                  <%= image_tag 'https://i.gyazo.com/d22ae1564aecc06fd22139bda8b53a09.gif', size: '300x200' %>
                  <p class="ttl"><%= link_to "Blog", six_content_tops_path, class: :function_list %></p>
                  <p class="description">Blogのサイトを模写しました。<br>ヘッダーをfixedを使用して固定するなど今まで自分の学んだことの無かったスキルも使用しました。また二分割レイアウトに関しても、もう一度学習しました。</p>
                </li>
              </ul>

              <%# 隙間 %>
                <div class="index_content_gap"></div>
              <%# 隙間 %>

              <ul class="list_feature">
                <li class="anime_up anime_op">
                  <%= image_tag 'white.png', size: '300x200' %>
                  <p class="ttl"><%= link_to "タイトル", root_path, class: :function_list %></p>
                  <p class="description">テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト</p>
                </li>
                <li class="anime_up anime_op">
                  <%= image_tag 'white.png', size: '300x200' %>
                  <p class="ttl"><%= link_to "タイトル", root_path, class: :function_list %></p>
                  <p class="description">テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト</p>
                </li>
                <li class="anime_up anime_op">
                  <%= image_tag 'white.png', size: '300x200' %>
                  <p class="ttl"><%= link_to "タイトル", root_path, class: :function_list %></p>
                  <p class="description">テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト</p>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    <%# Works %>

    <%# 隙間 %>
      <div class="area_gap"></div>
    <%# 隙間 %>

  <%# メイン %>

  </body>
</html>